### PR TITLE
update Introduction and Roadmap, add Development Guide and Screenshot 

### PR DESCRIPTION
**Pull request by FeynmanZhou**

### CODE REVIEW

**Comment by FeynmanZhou** [comment]
@rayzhou2017 @chilianyi Preview the updates from [README](https://github.com/FeynmanZhou/openpitrix/tree/refine-intro), [Development Guide](https://github.com/FeynmanZhou/openpitrix/blob/refine-intro/docs/development-guide.md), [Dashboard Screenshots](https://github.com/FeynmanZhou/openpitrix/blob/refine-intro/docs/op-screenshot.md)

**Comment by zheng1** [comment]
`.DS_Store` should be removed.

**Comment by FeynmanZhou** [comment]
> `.DS_Store` should be removed.

@zheng1 Removed.

**Comment by FeynmanZhou** [comment]
@ray
Could you pls help to review this PR ?

 Preview the updates from [README](https://github.com/FeynmanZhou/openpitrix/tree/refine-intro), [Development Guide](https://github.com/FeynmanZhou/openpitrix/blob/refine-intro/docs/development-guide.md), [Dashboard Screenshots](https://github.com/FeynmanZhou/openpitrix/blob/refine-intro/docs/op-screenshot.md)

**Pull request merged**
